package com.java.cursojava.config;

import java.time.Instant;
import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

import com.java.cursojava.entities.Category;
import com.java.cursojava.entities.Order;
import com.java.cursojava.entities.User;
import com.java.cursojava.entities.enums.OrderStatus;
import com.java.cursojava.repositories.CategoryRepository;
import com.java.cursojava.repositories.OrderRepository;
import com.java.cursojava.repositories.UserRepository;

//Auxiliary configuration class that is specific for the test profile

@Configuration
@Profile("test")
public class TestConfig implements CommandLineRunner { 
	// Implicit Dependency injection

	@Autowired
	private UserRepository userRepository;
	
	@Autowired
	private OrderRepository orderRepository;
	
	@Autowired
	private CategoryRepository categoryRepository;

	// Execute when application is initialized
	@Override
	public void run(String... args) throws Exception {
		
		//IDs are auto generated by the DB
		Category cat1 = new Category(null, "Electronics");
		Category cat2 = new Category(null, "Books");
		Category cat3 = new Category(null, "Computers");
		
		User u1 = new User(null, "Maria Brown", "maria@gmail.com", "988888888", "123456");
		User u2 = new User(null, "Alex Green", "alex@gmail.com", "977777777", "123456");
		
		Order o1 = new Order(null, Instant.parse("2019-06-20T19:53:07Z"), OrderStatus.DELIVERED ,u1);
		Order o2 = new Order(null, Instant.parse("2019-07-21T03:42:10Z"), OrderStatus.CANCELED, u2);
		Order o3 = new Order(null, Instant.parse("2019-07-22T15:21:22Z"), OrderStatus.SHIPPED, u1);
		
		//Saves in DB
		categoryRepository.saveAll(Arrays.asList(cat1, cat2, cat3));
		userRepository.saveAll(Arrays.asList(u1, u2));
		orderRepository.saveAll(Arrays.asList(o1, o2, o3));
	}

}
