package com.java.cursojava.config;

import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

import com.java.cursojava.entities.User;
import com.java.cursojava.repositories.UserRepository;

//Auxiliary configuration class that is specific for the test profile

@Configuration
@Profile("test")
public class TestConfig implements CommandLineRunner { 
	// Implicit Dependency injection

	@Autowired
	private UserRepository userRepository;

	// Execute when application is initialized
	@Override
	public void run(String... args) throws Exception {
		//ID auto generated by the DB
		User u1 = new User(null, "Maria Brown", "maria@gmail.com", "988888888", "123456");
		User u2 = new User(null, "Alex Green", "alex@gmail.com", "977777777", "123456");
		
		//Saves users in DB
		userRepository.saveAll(Arrays.asList(u1, u2));
	}

}
